# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da59116edf277e73ef4cdcb625dce8947fd3049a724587da1df4b5ccd6b3d605482f21fc807429d4f73a04925eaad7f35f7b38cbf15f590ff9ac7a5f52057fe2

test:
  secret_key_base: a6f5d9da509d4be04d528604ba1b7c330f0285704a16dc895dab449db2d7c00dd49b3f2e38111aa8ef5d44e8114e12673daf4aa95a41f8c63321f7bbcce06971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
